### ISSUE TITLE
Slideshow

### ISSUE THREAD

**Issue by Zeruxky** [CISOS-Team/CISOS-Tirol-Kliniken#16]
Found this page --> http://www.w3schools.com/howto/howto_js_slideshow.asp 
There is a simple tutorial for programming a slideshow. Maybe for display the menus at the screens.

**Comment by Zeruxky** [comment]
https://www.zdv.uni-mainz.de/1926.php ?

**Comment by Ryuuzei** [comment]
We have to configure the slide show right but this could work for displaying the menus.
There could be problems with the timing of changing.

**Comment by Zeruxky** [comment]
Testing it with a time interval of 15-20 sec. Or we can make three different websites (one for every menu) and make a automatic forwarding process. This would be an alternative to the slideshow. (see second link)

**Comment by Ryuuzei** [comment]
the problem here could be that during loading the new page there could be a small time window where you see a white page
for the first link we just have to calibrate it right then there shouldn't be a problem

**Comment by Zeruxky** [comment]
okay

**Comment by Zeruxky** [comment]
Can be closed or do you need this for the output at the monitors?
