### ISSUE TITLE
MenuInput

### ISSUE THREAD

**Issue by Zeruxky** [CISOS-Team/CISOS-Tirol-Kliniken#27]
Is the MenuInput.html for creating a menuplan? For example:
Monday: chicken wings
Tuesday: pizza
Wednesday: ...

Or can you input a new meal? For example:
Name: pizza
Type of meal: menu 1
Price: ....
Allergenic: ....

**Comment by Ryuuzei** [comment]
The Menu Input is for creating a new menu plan
not for inputing a  new meal.

**Comment by Zeruxky** [comment]
Should we take your design for the menuinput or mine?

**Comment by Ryuuzei** [comment]
I would take yours but I would make some changes 
It would exchange the search bar with a dropdown menu with the different menus
It makes things easier for the user and you still have the ability to search

**Comment by Ryuuzei** [comment]
In your current design are menu1 and menu 2 as "Hauptmenü" together but to put a meal in the right place shouldn't they be seperated?

**Comment by Zeruxky** [comment]
I think, menu1 and menu2 are the same. But we can separate it. 
I would keep the search bar, for a quick search and an drop-down-menu for scrolling throw the single entries.

**Comment by Ryuuzei** [comment]
Even if these are the same I think it would make things easier for the user if we separate them so he sees the difference between them.
