### ISSUE TITLE
Seperate Files ("Model-View-Controller")

### ISSUE THREAD

**Issue by Zeruxky** [CISOS-Team/CISOS-Tirol-Kliniken#31]
~~Maybe we  can implement something like Model-View-Controller (MVC). --> https://www.php-einfach.de/experte/objektorientierte-programmierung-oop/php-design-patterns/model-view-controller-in-php/~~

~~Is not required yet, but should be discussed.~~

We can forget the MVC (it's to complexe for this. If we want to use the MVC-method, we must use a framework like "Laravel"), but we should seperate the files like the comment above. If it's easy to seperate the files, then okay. If not, then make some little workarounds, but keep it small and simple.
We can write in our essay, that we pursued a similar idea (seperating html - css - php - javascript; coding style standard?)

**Comment by Ryuuzei** [comment]
it could make things easier.
Would you want to use it for every PHP-Files, because i think for some files it wouldn't make things much easier

**Comment by Zeruxky** [comment]
An alternative would be the programming language node.js --> http://nodecode.de/php-oder-nodejs
But we can make the backend-interface with php, would be easier for us, because we only learnt php.

For the MVC, we can discuss with our supervisor.

**Comment by Ryuuzei** [comment]
You're right it would be easier to work with PhP for now 

But we could discuss node.js with our supervisor

**Comment by Zeruxky** [comment]
MVC is implemented with following standards:
- html- files only include information, text, pictures and so on
- css-files only include informations about color, font, font-size and so on
- php-files only include database-related informations

**Comment by Zeruxky** [comment]
We can forget the MVC (it's to complexe for this. If we want to use the MVC-method, we must use a framework like "Laravel"), but we should seperate the files like the comment above. If it's easy to seperate the files, then okay. If not, then make some little workarounds, but keep it small and simple.
We can write in our essay, that we pursued a similar idea (seperating html - css - php - javascript; coding style standard?)

**Comment by Zeruxky** [comment]
Can we close this? All files are separated.
