### ISSUE TITLE
Database design

### ISSUE THREAD

**Issue by Zeruxky** [CISOS-Team/CISOS-Tirol-Kliniken#32]
We must think about the database design. It should have have following things:
- a table for the authenitfication
- a table for the meals
- a table for the drinks
- a (temporary-)table for saving the actual and following week (?)

For testing it on our own pc's, we should use XAMPP (The version must be identified with the company) and MySQL Workbench (Verison 6.3.7 --> https://dev.mysql.com/downloads/file/?id=463707 ).

**Comment by Ryuuzei** [comment]
Maybe we should split the meals into normal meals and vegitarian meals
It would give the database a lot more order

**Comment by Zeruxky** [comment]
Yeah, right. It would be make it easier for use to implement the database-query. We can filter then for normal meals and vegitarian meals.

**Comment by Ryuuzei** [comment]
Another idea would be if separate the meal - table in a three different tables for the different menus

**Comment by Ryuuzei** [comment]
by the way we should prioritise this because we need it for the other things like the authentification

**Comment by Zeruxky** [comment]
- [ yes] Authentification-table 
- [yes ] meal-table (more or less; colum for soup and drink is missing?)
- [ no] other things that should be implement

**Comment by Zeruxky** [comment]
We should use one method to name our tables and colums. Actually we have a few colums with german terms and other colums with english terms. 
And we should take care, that the colums are written correctly.

**Comment by Zeruxky** [comment]
Some things could be reworked (soup_data and so on for example).

**Comment by Ryuuzei** [comment]
new database design was handed out 
it is the final Version and there shouldn't be further changes

**Comment by Zeruxky** [comment]
Hopefully. Maybe we let this issue still open until to thursday next week .
