### ISSUE TITLE
3d-Model for the raspberry pi case

### ISSUE THREAD

**Issue by Zeruxky** [CISOS-Team/CISOS-Tirol-Kliniken#33]
We need also the 3d-Model for the raspberry pi case, for the HTL-Mensa. It should be made with the programms:
- OpenSCAD (http://www.openscad.org/)
- Dremel3D (https://dremel3d.de/pages/software)

The case should have have the color from the monitors.

**Comment by Ryuuzei** [comment]
Is it fixated that we use the raspberry or are we using another board

**Comment by Zeruxky** [comment]
The other alternatives are more expensive than the raspberry pi's, and a other reason is, that behind the raspberry pi-project is a large community, so we can find quick a workaround for a problem or something else.

**Comment by Zeruxky** [comment]
First prototype is made - more or less. Changing maybe some things (HDMI-Output, microUSB-Output and so on)?

**Comment by Ryuuzei** [comment]
Can be closed after printing the final version

**Comment by Zeruxky** [comment]
ok
