### ISSUE TITLE
Deamon-service

### ISSUE THREAD

**Issue by Zeruxky** [CISOS-Team/CISOS-Tirol-Kliniken#34]
We need also an deamon-service for the version for the raspberry pi's. Here we must ask our supervisor.

**Comment by Ryuuzei** [comment]
we should push it till later when we can talk to our supervisor again

**Comment by Zeruxky** [comment]
Okay. I will label it to: "doing later".

**Comment by Ryuuzei** [comment]
http://serverfault.com/questions/135859/is-there-a-standard-way-to-make-daemon-in-debian

this is a link that would describe on how to implement a daemon service on a debian/raspian system

**Comment by Zeruxky** [comment]
completed. The files to configure the raspberry will be pushed to a separate project.
