### ISSUE TITLE
Flexbox

### ISSUE THREAD

**Issue by Zeruxky** [CISOS-Team/CISOS-Tirol-Kliniken#37]
Maybe a easier way to create a responsive design?
https://wiki.selfhtml.org/wiki/CSS/Eigenschaften/Gr%C3%B6%C3%9Fenangaben/Flexbox

**Comment by Ryuuzei** [comment]
It sounds good, but i don't understand how you say what size your box should be

**Comment by Ryuuzei** [comment]
wait doesn't matter anymore found it

**Comment by Zeruxky** [comment]
Can be closed. It's only necessary for our essay (comparison between media queries and flexbox and so on)
